### ISSUE TITLE
AutoSNI LetsEncrypt Error: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by jefftham** [DylanPiercey/auto-sni#24]
i believe this is a great repo if it is really working.   
 Can you please take a look with the error that i got??

Thank you.

----------------------------------------------------------------------------------------------------
Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/www.ABC.com/privkey.pem'
    at Error (native)
----------------------------------------------------------------------------------------------------
[LE] register
[NLE]: begin registration
[le/core.js] try email
[le/core.js] create account
[le/core.js] created account
[le/core.js] privkeyPath /root/letsencrypt/etc/live/www.ABC.com/privkey.pem
[le/core.js] domainKeyPath: undefined
**AutoSNI LetsEncrypt Error: TypeError: Path must be a string. Received undefined**
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at /root/my-debian/Node_server/node_modules/letsencrypt/lib/core.js:274:31
    at tryCatcher (/root/my-debian/Node_server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/my-debian/Node_server/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/root/my-debian/Node_server/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/root/my-debian/Node_server/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/root/my-debian/Node_server/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/root/my-debian/Node_server/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/root/my-debian/Node_server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
Will fall back to self signed certificate.

______________
//server.js

var httpPort = 80;
var httpsPort = 443;

createServer({
    email: 'jeff.tham@email.com', // Emailed when certificates expire.
    agreeTos: true, // Required for letsencrypt.
    debug: true, // Add console messages and uses staging LetsEncrypt server. (Disable in production)
    domains: ["ABC.com", "test.ABC.com", "www.ABC.com"], // List of accepted domain names. (You can use nested arrays to register bundles with LE).
    forceSSL: true, // Make this false to disable auto http->https redirects (default true).
    redirectCode: 301, // If forceSSL is true, decide if redirect should be 301 (permanent) or 302 (temporary). Defaults to 302
    ports: {
        http: httpPort, // Optionally override the default http port.
        https: httpsPort // // Optionally override the default https port.
        }
    } ,app);

**Comment by DylanPiercey** [comment]
Which version of auto-sni are you using? Which os?

**Comment by jefftham** [comment]
512 MB Memory / 20 GB Disk / NYC3 - Debian 8.5 x64  ,   
and install through   
npm install auto-sni

, it should be the latest version because i just installed it.

**Comment by DylanPiercey** [comment]
And this error still exists after removing the debug option?

**Comment by shanoor** [comment]
I had the same error and the browser was showing a big warning (because of self-signed certificate). I disabled debug mode, it worked, I switched it back and now, there is no error and I have the debug.

**Comment by DylanPiercey** [comment]
@shanoor thanks, I don't think this is actually a bug, more debug mode being descriptive.

@jefftham I think this should only be an "issue" for your initial run. Debug mode will print all errors, and the first time you run the error is that the certificate doesn't exist.

I am going to close this issue, but if this is not the case please let me know. In theory running your code again should not have any errors (and it should have been working properly the first time).

**Comment by jefftham** [comment]
Thanks for you reply. Actually, the error is still occurred after i set the debug to false or delete the debug option. I really do not know why.

**Comment by jefftham** [comment]
A question, it takes how long to generate the letsencrypt's cert and key? is it happened because i visit the website before the cert and key exist? Then, forced it to generate self-signed cert and key?

**Comment by DylanPiercey** [comment]
I'll spend some more time digging when I get a chance, likely tomorrow.

**Comment by jefftham** [comment]
Thanks bro.

**Comment by sbugert** [comment]
I'm having the same issue.

Adding the `domainKeyPath` key to the args object around line 50 in lib/load.js seems to fix it.
I just hardcoded a path and the error disappeared.

Of course, this is not a real fix but maybe helps you tracking it down.

**Comment by DylanPiercey** [comment]
@jefftham @sbugert sorry for the delay.

I have released `auto-sni@1.5.0` which locks down the letsencrypt version and stops this issue. Once I get some time, I will upgrade this library to use `node-letsencrypt@2.0`. Help appreciated!

Let me know if this does not solve the issue for you guys.
